[mgr]
ratio          = [ 1, 2, 3 ]
sort_by        = "natural"
linemode       = "permissions"
show_hidden    = true

[opener]
edit = [
	{ run = 'nvim "$@"', desc = "$EDITOR", block = true, for = "unix" },
	{ run = 'code %*',    orphan = true, desc = "code",           for = "windows" },
	{ run = 'code -w %*', block = true,  desc = "code (block)",   for = "windows" },
]
